from selenium import webdriver
import pandas as pd
import database
import time
import os
def crwal(page,location):
    option = webdriver.ChromeOptions()
    option.add_argument("-incognito")
    driver = webdriver.Chrome()
    driver.get(page)
    time.sleep(5)
    cookiebtn=driver.find_element_by_xpath("//div[@class='close-cookie']")
    cookiebtn.click()
    time.sleep(2)
    change=driver.find_element_by_xpath("//button[@class='btn btn--primary']")
    change.click()
    time.sleep(2)
    change=driver.find_element_by_xpath("//button[@class='btn btn--primary']")
    change.click()
    time.sleep(2)
    change=driver.find_element_by_xpath("//button[@class='btn btn--primary']")
    change.click()
    time.sleep(2)
    lst=driver.find_element_by_xpath("//input[@class='cy db bn dc dd gk d3 b1 an cp d8 d9 c9 cb cc ca c7 c8 bt bw']")
    lst.click()
    popup=driver.find_elements_by_xpath("//ul[@role='listbox']/li")
    popup[location].click()
    time.sleep(5)
    time.sleep(2)
    data=driver.find_element_by_xpath("//button[@class='ce ae b5 ag bz az ay bc an ep eq er es et d9 eu ev cr cs b4 ew ex ey ez f0 f1 f2 f3 f4 f5 f6 f7 cc c9 ca cb d0 eo cf f8 f9 fa']")
    data.click()
    time.sleep(3)
    downloadbtn=driver.find_elements_by_xpath("//button[@class='btn btn--link hard--left push-tiny--right']")
    downloadbtn[0].click()
    time.sleep(3)
    text_area = driver.find_element_by_id('firstName')
    text_area.send_keys("Iuahuiwfiawnxui")
    text_area = driver.find_element_by_id('lastName')
    text_area.send_keys("Wxhjvfgpd")
    text_area = driver.find_element_by_id('email')
    text_area.send_keys("j@j.com")
    text_area = driver.find_element_by_id('role')
    text_area.send_keys("Analyst")
    text_area = driver.find_element_by_id('plannedUsage')
    text_area.send_keys("Analysis")
    purpose=driver.find_element_by_xpath("//div[@class='bj cz d0 d1 d2 c2 d3 ch d4 d5 d6 cx d7 bw']")
    purpose.click()
    purpose=driver.find_element_by_xpath("//li[@class='ae b5 ag bz ce c6 c2 b4 je jf cr cs cb ez f0 f2 f1 b2']")
    purpose.click()
    time.sleep(1)
    change=driver.find_element_by_xpath("//button[@type='submit']")
    change.click()
    time.sleep(3)
    close_button=driver.find_element_by_xpath("//button[@aria-label='Close']")
    close_button.click()
    print("DATA IS DOWNLOADED SUCCESSFULLY")
    driver.quit()
    time.sleep(1)
    print("Processing...")
    time.sleep(3)
    database.show_data()
    delete_file()
def delete_file():
    os.chdir('/home/sachin/Downloads')
    os.remove('Travel_Times.csv')


